name: Deploy complex
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Log in to the docker CLI
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t linakrasko/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true linakrasko/react-test npm test

      - run: docker build -t linakrasko/multi-client ./client
      - run: docker build -t linakrasko/multi-nginx ./nginx
      - run: docker build -t linakrasko/multi-worker ./worker
      - run: docker build -t linakrasko/multi-server ./server

      - run: docker push -t linakrasko/multi-client
      - run: docker push -t linakrasko/multi-nginx
      - run: docker push -t linakrasko/multi-worker
      - run: docker push -t linakrasko/multi-server
